### ISSUE TITLE
FLUX gguf models not being detected/not working

### ISSUE THREAD

**Issue by UnconnectedBedna** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#144]
Everything seems to work with civitai-helper except for flux gguf models.
Are there plans to include them as well?

This is such a useful tool to gather info on models/loras/textual inversions/etc, would be great if my downloaded flux models could also be "automatically" populated with info and image.

**Comment by zixaphir** [comment]
I'm adding support for scanning them but some GGUF models currently distribute as *.zip files. Once extracted, they won't be able to be scanned because Civitai doesn't know the fingerprint of the actual model, just the containing zip. If this happens, please bug the model author to re-upload their model as *.gguf on Civitai, as Civitai seems to support the format now.

**Comment by zixaphir** [comment]
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/617841dd596943344de02594d858120b54fd51b0

**Comment by UnconnectedBedna** [comment]
> I'm adding support for scanning them but some GGUF models currently distribute as *.zip files. Once extracted, they won't be able to be scanned because Civitai doesn't know the fingerprint of the actual model, just the containing zip. If this happens, please bug the model author to re-upload their model as *.gguf on Civitai, as Civitai seems to support the format now.

Oh, you are right, ofc!
I didn't think about the files being zip on civitai!

Thank you for the response and I'll see if I can get one of the uploaders to change into raw format instead of zip to test if it works! :)

Lets close this issue.
